youtubeData:
  ## provide multiple api key in case any key get exhausted next key would be automatically picked up
  key:
    - "AIzaSyDaeGxZ3qB3xHsMfxiIHYi_A0ND453ma1k"
    - "AIzaSyDaeGxZ3qB3xHsMfxiIHYi_A0ND453ma1k"
    - "AIzaSyDaeGxZ3qB3xHsMfxiIHYi_A0ND453ma1k"
    - "AIzaSyBrNkJ5oRtnLTNMGy1D0x5lnMmODyHkJP0"
  topics:
    - "Xavi"
    - "Barcelona"
    - "Klopp"
    - "Kohli"
    - "Champions League"
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "root"

api:
  default-page: 0
  default-size: 10